name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/api/requirements.txt
      
      - name: Build Docker Image
        run: |
          docker build -t image-classification-app:latest -f deployment/docker/Dockerfile .

      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag image-classification-app:latest $DOCKER_USERNAME/image-classification-app:latest
          docker push $DOCKER_USERNAME/image-classification-app:latest

      - name: Deploy to AWS
        run: |
          python deployment/scripts/deploy_aws.py

      - name: Deploy to GCP
        run: |
          python deployment/scripts/deploy_gcp.py